---
abstract: 'Simple user sessions management'
author:
  - 'Gunnar Wolf <gwolf@gwolf.org>'
build_requires:
  DBD::SQLite: 0
  Module::Build: 0
  Test::Pod: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: User-Simple
provides:
  User::Simple:
    file: lib/User/Simple.pm
    version: 1.45
  User::Simple::Admin:
    file: lib/User/Simple/Admin.pm
    version: 0
requires:
  DBI: 0
  Date::Calc: 0
  Digest::MD5: 0
resources:
  license: http://dev.perl.org/licenses/
version: 1.45
